# yaml-language-server: $schema=https://registry.semrel.io/schemas/core/v1.json
schemaVersion: 1

branches:
  - name: main

tagPrefix: v

## These are the default rules...
# rules:
#   - type: feat
#     bump: minor
#   - type: fix
#     bump: patch
#   - type: perf
#     bump: patch
#   - type: revert
#     bump: patch

# commit_changelog: false  # handled by generator-changelog-md plugin

plugins:
  - uses: '@semrel/analyzer-conventional'

  ## NOTE: neither generator-release-notes nor generator-changelog-md seems to
  ## do anything different from the default semrel behavior

  # - uses: '@semrel/generator-release-notes'
  #   phase: generator
  #   args:
  #     signature: "true"

  # - uses: '@semrel/generator-changelog-md'
  #   # yaml-language-server: $schema=https://registry.semrel.io/schemas/plugins/generator-changelog-md/latest.json
  #   phase: pre-tag
  #   args:
  #     # keep_releases: "3"
  #     signature: "true"
  #     group_by_type: "true"
  #     file: CHANGELOG.md

  - uses: '@semrel/condition-github-actions'
    phase: condition

  - uses: '@semrel/provider-github'

  - uses: '@semrel/hook-slack'
    args:
      webhook_url: '{{ env "SLACK_WEBHOOK_URL" }}'
