version: "3"

# Since this is a library, we don't really build anything regularly... our
# distribution is the raw source-code itself.  Nonetheless, we have tasks for
# useful things like testing, running the example, etc.
#
# `task` is listed as a tool in the `go.mod` file, so you can run `go tool task
# ...` if you don't have `task` installed yourself.

vars:
  COVERAGE_DIR: ./coverage

tasks:
  default:
    cmds:
      - go tool task --list

  prepare:
    desc: One-time local repo setup
    cmds:
      - go mod download
      - go tool husky install

  clean:
    desc: Clean project
    cmds:
      - rm -rf {{.COVERAGE_DIR}}
      - rm -rf .task

  coveragedir:
    desc: Create coverage directory
    cmds:
      - mkdir {{.COVERAGE_DIR}}
    status:
      - test -d {{.COVERAGE_DIR}}

  test:
    desc: Test project
    deps:
      - coveragedir
    cmds:
      - go test -coverprofile {{.COVERAGE_DIR}}/cover.out ./...
      - go tool cover -html {{.COVERAGE_DIR}}/cover.out -o {{.COVERAGE_DIR}}/coverage.html

  security:
    desc: Check code and dependencies for security issues
    cmds:
      - cmd: echo "checking source for known mistakes..."
        silent: true
      - go tool gosec -quiet ./...
      - cmd: echo "checking dependency vulnerabilities..."
        silent: true
      # govulncheck gives a warning about golang.org/x/crypto/openpgp, but
      # *nothing* is pulling that in.
      - go tool govulncheck -show verbose,color ./...
      - cmd: echo "If only GO-2026-5932 for golang.org/x/crypto/openpgp was shown, that's okay."
        silent: true

  pre-commit:
    desc: Run pre-commit checks...
    deps:
      - test
      - security ## bogus internal error in gosec?
    cmds:
      - go vet ./...

  example:help:
    desc: Quick-run the example to show help
    aliases: [help]
    cmds:
      - go run example/main.go --help

  example:run:
    desc: Run the example
    aliases: [run]
    cmds:
      - go run example/main.go {{.CLI_ARGS}}

  example:run:child:
    desc: Run the example
    aliases: [run]
    cmds:
      - go run example/main.go child {{.CLI_ARGS}}

  example:run:config:
    desc: Run the example
    aliases: [run]
    cmds:
      - go run example/main.go --config example/ad-hoc-config.yaml {{.CLI_ARGS}}

  release:
    desc: Run a snapshot (test) release
    cmds:
      - goreleaser release --snapshot --clean
