version: "3"

# Since this is a library, we don't really build anything regularly... our
# distribution is the raw source-code itself.  Nonetheless, we have tasks for
# useful things like testing, running the example, etc.

vars:
  COVERAGE_DIR: ./coverage

tasks:
  default:
    cmds:
      - task: run

  clean:
    desc: Clean project
    cmds:
      - rm -rf {{.COVERAGE_DIR}}
      - rm -rf .task

  coveragedir:
    desc: Create coverage directory
    cmds:
      - mkdir {{.COVERAGE_DIR}}
    status:
      - test -d {{.COVERAGE_DIR}}

  test:
    desc: Test project
    deps:
      - coveragedir
    cmds:
      - go test -coverprofile {{.COVERAGE_DIR}}/cover.out ./...
      - go tool cover -html {{.COVERAGE_DIR}}/cover.out -o {{.COVERAGE_DIR}}/coverage.html

  security:
    desc: Run gosec for project
    cmds:
      - gosec -quiet ./...

  pre-commit:
    desc: Run pre-commit checks...
    deps:
      - test
      - security
    cmds:
      - go vet ./...

  help:
    desc: Quick-run the example to show help
    cmds:
      - go run example/main.go --help

  run:
    desc: Run the example
    cmds:
      - go run example/main.go
