name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: download dependencies, test, and validate security
        run: |
          go mod download
          go tool task test
          go tool task security

      - uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        name: release
        run: |
          git config user.name "SemRel Bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          go tool semrel release --output-file .release.json

          if [[ "$(jq -r '.released' .release.json)" = "true" ]]; then
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
